bazel_dep(name = "rules_java", version = "9.1.0")
bazel_dep(name = "rules_jvm_external", version = "6.7")

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

graalvm_ext = use_extension("//:graalvm_extension.bzl", "graalvm_ext")
use_repo(graalvm_ext, "graalvm")

maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.install(
    artifacts = [
        "org.projectlombok:lombok:1.18.30",
        "com.google.dagger:dagger:2.51.1",
        "com.google.dagger:dagger-compiler:2.51.1",
        "info.picocli:picocli:4.7.7",
        "info.picocli:picocli-codegen:4.7.7",
        "junit:junit:4.13.2",
        "org.openjfx:javafx-controls:23.0.2",
        "org.openjfx:javafx-fxml:23.0.2",
        "org.openjfx:javafx-graphics:23.0.2",
        "org.openjfx:javafx-base:23.0.2",
        "org.openjfx:javafx-graphics:23.0.2:linux",
        "org.openjfx:javafx-graphics:23.0.2:mac",
        "org.openjfx:javafx-graphics:23.0.2:win",
    ],
    repositories = [
        "https://repo1.maven.org/maven2",
    ],
)
use_repo(maven, "maven")
