def _native_image_impl(ctx):
    is_windows = ctx.configuration.host_path_separator == ";"
    
    # 1. Ensure out_name ends with .exe on Windows (without duplicating it)
    base_name = ctx.label.name
    if is_windows and not base_name.lower().endswith(".exe"):
        out_name = base_name + ".exe"
    else:
        out_name = base_name

    out_binary = ctx.actions.declare_file(out_name)

    # 2. Strip .exe for -H:Name on Windows because native-image auto-appends .exe on Windows
    h_name_path = out_binary.path
    if is_windows and h_name_path.lower().endswith(".exe"):
        h_name_path = h_name_path[:-4]

    jar_file = ctx.file.jar

    inputs = [jar_file]

    args = ctx.actions.args()
    args.add("-jar", jar_file.path)
    args.add("-H:Name=" + h_name_path)

    sep = ctx.configuration.host_path_separator

    # 3. Pass GraalVM configuration files (JNI / reflection / resources / serialization)
    # generated by the native-image tracing agent.
    config_specs = [
        ("jni_config", "JNIConfigurationFiles"),
        ("reflection_config", "ReflectionConfigurationFiles"),
        ("resource_config", "ResourceConfigurationFiles"),
        ("serialization_config", "SerializationConfigurationFiles"),
    ]

    for attr_name, flag_name in config_specs:
        files = getattr(ctx.files, attr_name)
        if files:
            inputs.extend(files)
            args.add("-H:%s=%s" % (flag_name, sep.join([f.path for f in files])))

    for extra_arg in ctx.attr.extra_args:
        args.add(extra_arg)

    ctx.actions.run(
        outputs = [out_binary],
        inputs = inputs,
        executable = ctx.executable._native_image_tool,
        arguments = [args],
        mnemonic = "GraalVMNativeImage",
        progress_message = "Building GraalVM native image %s" % ctx.label.name,
        use_default_shell_env = True,
    )

    return [DefaultInfo(executable = out_binary)]

native_image = rule(
    implementation = _native_image_impl,
    executable = True,
    attrs = {
        "jar": attr.label(
            mandatory = True,
            allow_single_file = [".jar"],
        ),
        "jni_config": attr.label_list(
            allow_files = [".json"],
        ),
        "reflection_config": attr.label_list(
            allow_files = [".json"],
        ),
        "resource_config": attr.label_list(
            allow_files = [".json"],
        ),
        "serialization_config": attr.label_list(
            allow_files = [".json"],
        ),
        "extra_args": attr.string_list(default = []),
        "_native_image_tool": attr.label(
            default = Label("@graalvm//:native_image_tool"),
            allow_single_file = True,
            executable = True,
            cfg = "exec",
        ),
    },
)
