load("@rules_java//java:defs.bzl", "java_test")

package(default_visibility = ["//visibility:public"])

java_test(
    name = "ImageReaderTest",
    srcs = ["ImageReaderTest.java"],
    deps = [
        "//java/com/cowlark/fluxengine/config",
        "//java/com/cowlark/fluxengine/config:common_java_proto",
        "//java/com/cowlark/fluxengine/config:config_java_proto",
        "//java/com/cowlark/fluxengine/core",
        "//java/com/cowlark/fluxengine/data",
        "//java/com/cowlark/fluxengine/imagereader",
        "//java/com/cowlark/fluxengine/imagereader:imagereader_java_proto",
        "//javatests/com/cowlark/fluxengine/testing",
        "@com_google_protobuf//java/core",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)
