from build.c import clibrary

clibrary(
    name="adflib",
    srcs=[
        "./src/adf_bitm.c",
        "./src/adf_bitm.h",
        "./src/adf_cache.c",
        "./src/adf_cache.h",
        "./src/adf_dir.c",
        "./src/adf_dir.h",
        "./src/adf_disk.c",
        "./src/adf_disk.h",
        "./src/adf_dump.c",
        "./src/adf_dump.h",
        "./src/adf_env.c",
        "./src/adf_env.h",
        "./src/adf_file.c",
        "./src/adf_file.h",
        "./src/adf_hd.c",
        "./src/adf_hd.h",
        "./src/adf_link.c",
        "./src/adf_link.h",
        "./src/adf_raw.c",
        "./src/adf_raw.h",
        "./src/adf_salv.c",
        "./src/adf_salv.h",
        "./src/adf_str.h",
        "./src/adf_util.c",
        "./src/adf_util.h",
        "./src/defendian.h",
        "./src/hd_blk.h",
        "./src/prefix.h",
        "./adf_nativ.h",
        "./config.h",
        "./src/adflib.h",
    ],
    cflags=["-Idep/adflib", "-Idep/adflib/src"],
    hdrs={
        "adf_blk.h": "./src/adf_blk.h",
        "adf_defs.h": "./src/adf_defs.h",
        "adf_err.h": "./src/adf_err.h",
        "adf_nativ.h": "./adf_nativ.h",
        "adf_str.h": "./src/adf_str.h",
        "adflib.h": "./src/adflib.h",
    },
)
