load("@rules_java//java:defs.bzl", "java_test")

package(default_visibility = ["//visibility:public"])

java_test(
    name = "Fl2FluxSinkTest",
    srcs = ["Fl2FluxSinkTest.java"],
    deps = [
        "//javatests/com/cowlark/fluxengine/testing",
        "//java/com/cowlark/fluxengine/config",
        "//java/com/cowlark/fluxengine/config:config_java_proto",
        "//java/com/cowlark/fluxengine/core",
        "//java/com/cowlark/fluxengine/data",
        "//java/com/cowlark/fluxengine/external:fl2_java_proto",
        "//java/com/cowlark/fluxengine/fluxsink",
        "//java/com/cowlark/fluxengine/fluxsink:fluxsink_java_proto",
        "@com_google_protobuf//java/core",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)

java_test(
    name = "FluxSinkTest",
    srcs = ["FluxSinkTest.java"],
    deps = [
        "//javatests/com/cowlark/fluxengine/testing",
        "//java/com/cowlark/fluxengine/config",
        "//java/com/cowlark/fluxengine/config:config_java_proto",
        "//java/com/cowlark/fluxengine/core",
        "//java/com/cowlark/fluxengine/data",
        "//java/com/cowlark/fluxengine/external",
        "//java/com/cowlark/fluxengine/fluxsink",
        "//java/com/cowlark/fluxengine/fluxsink:fluxsink_java_proto",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)
