load("@com_google_protobuf//bazel:java_proto_library.bzl", "java_proto_library")
load("@rules_java//java:defs.bzl", "java_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "fluxsource_proto",
    srcs = ["fluxsource.proto"],
    strip_import_prefix = "/java/",
    deps = ["//java/com/cowlark/fluxengine/config:common_proto"],
)

java_proto_library(
    name = "fluxsource_java_proto",
    deps = [":fluxsource_proto"],
)

java_library(
    name = "fluxsource",
    srcs = glob(["*.java"]),
    deps = [
        ":fluxsource_java_proto",
        "//java/com/cowlark/fluxengine/config",
        "//java/com/cowlark/fluxengine/config:common_java_proto",
        "//java/com/cowlark/fluxengine/core",
        "//java/com/cowlark/fluxengine/data",
    ],
)
