load("@rules_java//java:defs.bzl", "java_test")

package(default_visibility = ["//visibility:public"])

java_test(
    name = "UsbFactoryTest",
    srcs = ["UsbFactoryTest.java"],
    deps = [
        "//java/com/cowlark/fluxengine/config",
        "//java/com/cowlark/fluxengine/config:config_java_proto",
        "//java/com/cowlark/fluxengine/usb",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)
