package(default_visibility = ["//visibility:public"])

# Per-package BUILD for Java tests in com.cowlark.fluxengine
java_test(
    name = "fluxengine_tests",
    srcs = glob(["*.java"]),
    deps = [
        "//java/com/cowlark/fluxengine:fluxengine_lib",
        "@maven//:junit_junit",
    ],
    plugins = ["//java/com/cowlark/fluxengine:dagger_plugin"],
)
