load("@rules_java//java:defs.bzl", "java_library", "java_plugin")

package(default_visibility = ["//visibility:public"])

java_plugin(
    name = "picocli",
    processor_class = "picocli.codegen.aot.graalvm.processor.NativeImageConfigGeneratorProcessor",
    deps = ["@maven//:info_picocli_picocli_codegen"],
)

java_library(
    name = "cli",
    srcs = glob(["*.java"]),
    plugins = [":picocli"],
    deps = [
        "//java/com/cowlark/fluxengine/usb",
        "//java/com/cowlark/fluxengine/wiring:component",
        "@maven//:com_google_guava_guava",
        "@maven//:info_picocli_picocli",
    ],
)
