load("@rules_java//java:defs.bzl", "java_test")

package(default_visibility = ["//visibility:public"])

java_test(
    name = "FluxmapTest",
    srcs = ["FluxmapTest.java"],
    deps = [
        "//java/com/cowlark/fluxengine/core",
        "//java/com/cowlark/fluxengine/data",
        "//java/com/cowlark/fluxengine/external",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)

java_test(
    name = "FluxmapReaderTest",
    srcs = ["FluxmapReaderTest.java"],
    deps = [
        "//java/com/cowlark/fluxengine/core",
        "//java/com/cowlark/fluxengine/data",
        "//java/com/cowlark/fluxengine/decoders:decoders_java_proto",
        "//java/com/cowlark/fluxengine/external",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)

java_test(
    name = "LocationsTest",
    srcs = ["LocationsTest.java"],
    deps = [
        "//java/com/cowlark/fluxengine/core",
        "//java/com/cowlark/fluxengine/data",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)

java_test(
    name = "DiskLayoutTest",
    srcs = ["DiskLayoutTest.java"],
    deps = [
        "//java/com/cowlark/fluxengine/config:config_java_proto",
        "//java/com/cowlark/fluxengine/config:drive_java_proto",
        "//java/com/cowlark/fluxengine/config:layout_java_proto",
        "//java/com/cowlark/fluxengine/data",
        "//java/com/cowlark/fluxengine/external:fl2_java_proto",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)

java_test(
    name = "KryofluxTest",
    srcs = ["KryofluxTest.java"],
    deps = [
        "//java/com/cowlark/fluxengine/core",
        "//java/com/cowlark/fluxengine/data",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)
