load("@rules_java//java:defs.bzl", "java_library")

package(default_visibility = ["//visibility:public"])

java_library(
    name = "data",
    srcs = glob(["*.java"]),
    deps = [
        "//java/com/cowlark/fluxengine/core",
        "//java/com/cowlark/fluxengine/decoders:decoders_java_proto",
        "//java/com/cowlark/fluxengine/external",
        "@maven//:com_google_guava_guava",
    ],
)
