load("@rules_java//java:defs.bzl", "java_test")

package(default_visibility = ["//visibility:public"])

java_test(
    name = "FluxDecoderTest",
    srcs = ["FluxDecoderTest.java"],
    deps = [
        "//java/com/cowlark/fluxengine/core",
        "//java/com/cowlark/fluxengine/data",
        "//java/com/cowlark/fluxengine/decoders",
        "//java/com/cowlark/fluxengine/decoders:decoders_java_proto",
        "//java/com/cowlark/fluxengine/external",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)