from build.c import cxxlibrary

cxxlibrary(
    name="agg",
    srcs=[
        "./src/agg_arrowhead.cpp",
        "./src/agg_line_aa_basics.cpp",
        "./src/agg_vcgen_bspline.cpp",
        "./src/agg_vpgen_segmentator.cpp",
        "./src/agg_color_rgba.cpp",
        "./src/agg_sqrt_tables.cpp",
        "./src/agg_bspline.cpp",
        "./src/agg_curves.cpp",
        "./src/agg_rounded_rect.cpp",
        "./src/agg_vcgen_markers_term.cpp",
        "./src/agg_vcgen_dash.cpp",
        "./src/agg2d.cpp",
        "./src/agg_trans_affine.cpp",
        "./src/agg_gsv_text.cpp",
        "./src/agg_vcgen_smooth_poly1.cpp",
        "./src/agg_trans_single_path.cpp",
        "./src/agg_vpgen_clip_polygon.cpp",
        "./src/agg_embedded_raster_fonts.cpp",
        "./src/agg_trans_double_path.cpp",
        "./src/agg_vcgen_stroke.cpp",
        "./src/agg_arc.cpp",
        "./src/agg_image_filters.cpp",
        "./src/agg_trans_warp_magnifier.cpp",
        "./src/agg_vpgen_clip_polyline.cpp",
        "./src/agg_bezier_arc.cpp",
        "./src/agg_line_profile_aa.cpp",
        "./src/agg_vcgen_contour.cpp",
    ],
    hdrs={
        "agg2d.h": "./include/agg2d.h",
        "agg_alpha_mask_u8.h": "./include/agg_alpha_mask_u8.h",
        "agg_arc.h": "./include/agg_arc.h",
        "agg_array.h": "./include/agg_array.h",
        "agg_arrowhead.h": "./include/agg_arrowhead.h",
        "agg_basics.h": "./include/agg_basics.h",
        "agg_bezier_arc.h": "./include/agg_bezier_arc.h",
        "agg_bitset_iterator.h": "./include/agg_bitset_iterator.h",
        "agg_blur.h": "./include/agg_blur.h",
        "agg_bounding_rect.h": "./include/agg_bounding_rect.h",
        "agg_bspline.h": "./include/agg_bspline.h",
        "agg_clip_liang_barsky.h": "./include/agg_clip_liang_barsky.h",
        "agg_color_gray.h": "./include/agg_color_gray.h",
        "agg_color_rgba.h": "./include/agg_color_rgba.h",
        "agg_config.h": "./include/agg_config.h",
        "agg_conv_adaptor_vcgen.h": "./include/agg_conv_adaptor_vcgen.h",
        "agg_conv_adaptor_vpgen.h": "./include/agg_conv_adaptor_vpgen.h",
        "agg_conv_bspline.h": "./include/agg_conv_bspline.h",
        "agg_conv_clip_polygon.h": "./include/agg_conv_clip_polygon.h",
        "agg_conv_clip_polyline.h": "./include/agg_conv_clip_polyline.h",
        "agg_conv_close_polygon.h": "./include/agg_conv_close_polygon.h",
        "agg_conv_concat.h": "./include/agg_conv_concat.h",
        "agg_conv_contour.h": "./include/agg_conv_contour.h",
        "agg_conv_curve.h": "./include/agg_conv_curve.h",
        "agg_conv_dash.h": "./include/agg_conv_dash.h",
        "agg_conv_gpc.h": "./include/agg_conv_gpc.h",
        "agg_conv_marker_adaptor.h": "./include/agg_conv_marker_adaptor.h",
        "agg_conv_marker.h": "./include/agg_conv_marker.h",
        "agg_conv_segmentator.h": "./include/agg_conv_segmentator.h",
        "agg_conv_shorten_path.h": "./include/agg_conv_shorten_path.h",
        "agg_conv_smooth_poly1.h": "./include/agg_conv_smooth_poly1.h",
        "agg_conv_stroke.h": "./include/agg_conv_stroke.h",
        "agg_conv_transform.h": "./include/agg_conv_transform.h",
        "agg_conv_unclose_polygon.h": "./include/agg_conv_unclose_polygon.h",
        "agg_curves.h": "./include/agg_curves.h",
        "agg_dda_line.h": "./include/agg_dda_line.h",
        "agg_ellipse_bresenham.h": "./include/agg_ellipse_bresenham.h",
        "agg_ellipse.h": "./include/agg_ellipse.h",
        "agg_embedded_raster_fonts.h": "./include/agg_embedded_raster_fonts.h",
        "agg_font_cache_manager2.h": "./include/agg_font_cache_manager2.h",
        "agg_font_cache_manager.h": "./include/agg_font_cache_manager.h",
        "agg_gamma_functions.h": "./include/agg_gamma_functions.h",
        "agg_gamma_lut.h": "./include/agg_gamma_lut.h",
        "agg_glyph_raster_bin.h": "./include/agg_glyph_raster_bin.h",
        "agg_gradient_lut.h": "./include/agg_gradient_lut.h",
        "agg_gsv_text.h": "./include/agg_gsv_text.h",
        "agg_image_accessors.h": "./include/agg_image_accessors.h",
        "agg_image_filters.h": "./include/agg_image_filters.h",
        "agg_line_aa_basics.h": "./include/agg_line_aa_basics.h",
        "agg_math.h": "./include/agg_math.h",
        "agg_math_stroke.h": "./include/agg_math_stroke.h",
        "agg_path_length.h": "./include/agg_path_length.h",
        "agg_path_storage.h": "./include/agg_path_storage.h",
        "agg_path_storage_integer.h": "./include/agg_path_storage_integer.h",
        "agg_pattern_filters_rgba.h": "./include/agg_pattern_filters_rgba.h",
        "agg_pixfmt_amask_adaptor.h": "./include/agg_pixfmt_amask_adaptor.h",
        "agg_pixfmt_base.h": "./include/agg_pixfmt_base.h",
        "agg_pixfmt_gray.h": "./include/agg_pixfmt_gray.h",
        "agg_pixfmt_rgba.h": "./include/agg_pixfmt_rgba.h",
        "agg_pixfmt_rgb.h": "./include/agg_pixfmt_rgb.h",
        "agg_pixfmt_rgb_packed.h": "./include/agg_pixfmt_rgb_packed.h",
        "agg_pixfmt_transposer.h": "./include/agg_pixfmt_transposer.h",
        "agg_rasterizer_cells_aa.h": "./include/agg_rasterizer_cells_aa.h",
        "agg_rasterizer_compound_aa.h": "./include/agg_rasterizer_compound_aa.h",
        "agg_rasterizer_outline_aa.h": "./include/agg_rasterizer_outline_aa.h",
        "agg_rasterizer_outline.h": "./include/agg_rasterizer_outline.h",
        "agg_rasterizer_scanline_aa.h": "./include/agg_rasterizer_scanline_aa.h",
        "agg_rasterizer_scanline_aa_nogamma.h": "./include/agg_rasterizer_scanline_aa_nogamma.h",
        "agg_rasterizer_sl_clip.h": "./include/agg_rasterizer_sl_clip.h",
        "agg_renderer_base.h": "./include/agg_renderer_base.h",
        "agg_renderer_markers.h": "./include/agg_renderer_markers.h",
        "agg_renderer_mclip.h": "./include/agg_renderer_mclip.h",
        "agg_renderer_outline_aa.h": "./include/agg_renderer_outline_aa.h",
        "agg_renderer_outline_image.h": "./include/agg_renderer_outline_image.h",
        "agg_renderer_primitives.h": "./include/agg_renderer_primitives.h",
        "agg_renderer_raster_text.h": "./include/agg_renderer_raster_text.h",
        "agg_renderer_scanline.h": "./include/agg_renderer_scanline.h",
        "agg_rendering_buffer_dynarow.h": "./include/agg_rendering_buffer_dynarow.h",
        "agg_rendering_buffer.h": "./include/agg_rendering_buffer.h",
        "agg_rounded_rect.h": "./include/agg_rounded_rect.h",
        "agg_scanline_bin.h": "./include/agg_scanline_bin.h",
        "agg_scanline_boolean_algebra.h": "./include/agg_scanline_boolean_algebra.h",
        "agg_scanline_p.h": "./include/agg_scanline_p.h",
        "agg_scanline_storage_aa.h": "./include/agg_scanline_storage_aa.h",
        "agg_scanline_storage_bin.h": "./include/agg_scanline_storage_bin.h",
        "agg_scanline_u.h": "./include/agg_scanline_u.h",
        "agg_shorten_path.h": "./include/agg_shorten_path.h",
        "agg_simul_eq.h": "./include/agg_simul_eq.h",
        "agg_span_allocator.h": "./include/agg_span_allocator.h",
        "agg_span_converter.h": "./include/agg_span_converter.h",
        "agg_span_gouraud_gray.h": "./include/agg_span_gouraud_gray.h",
        "agg_span_gouraud.h": "./include/agg_span_gouraud.h",
        "agg_span_gouraud_rgba.h": "./include/agg_span_gouraud_rgba.h",
        "agg_span_gradient_alpha.h": "./include/agg_span_gradient_alpha.h",
        "agg_span_gradient_contour.h": "./include/agg_span_gradient_contour.h",
        "agg_span_gradient.h": "./include/agg_span_gradient.h",
        "agg_span_gradient_image.h": "./include/agg_span_gradient_image.h",
        "agg_span_image_filter_gray.h": "./include/agg_span_image_filter_gray.h",
        "agg_span_image_filter.h": "./include/agg_span_image_filter.h",
        "agg_span_image_filter_rgba.h": "./include/agg_span_image_filter_rgba.h",
        "agg_span_image_filter_rgb.h": "./include/agg_span_image_filter_rgb.h",
        "agg_span_interpolator_adaptor.h": "./include/agg_span_interpolator_adaptor.h",
        "agg_span_interpolator_linear.h": "./include/agg_span_interpolator_linear.h",
        "agg_span_interpolator_persp.h": "./include/agg_span_interpolator_persp.h",
        "agg_span_interpolator_trans.h": "./include/agg_span_interpolator_trans.h",
        "agg_span_pattern_gray.h": "./include/agg_span_pattern_gray.h",
        "agg_span_pattern_rgba.h": "./include/agg_span_pattern_rgba.h",
        "agg_span_pattern_rgb.h": "./include/agg_span_pattern_rgb.h",
        "agg_span_solid.h": "./include/agg_span_solid.h",
        "agg_span_subdiv_adaptor.h": "./include/agg_span_subdiv_adaptor.h",
        "agg_trans_affine.h": "./include/agg_trans_affine.h",
        "agg_trans_bilinear.h": "./include/agg_trans_bilinear.h",
        "agg_trans_double_path.h": "./include/agg_trans_double_path.h",
        "agg_trans_perspective.h": "./include/agg_trans_perspective.h",
        "agg_trans_single_path.h": "./include/agg_trans_single_path.h",
        "agg_trans_viewport.h": "./include/agg_trans_viewport.h",
        "agg_trans_warp_magnifier.h": "./include/agg_trans_warp_magnifier.h",
        "agg_vcgen_bspline.h": "./include/agg_vcgen_bspline.h",
        "agg_vcgen_contour.h": "./include/agg_vcgen_contour.h",
        "agg_vcgen_dash.h": "./include/agg_vcgen_dash.h",
        "agg_vcgen_markers_term.h": "./include/agg_vcgen_markers_term.h",
        "agg_vcgen_smooth_poly1.h": "./include/agg_vcgen_smooth_poly1.h",
        "agg_vcgen_stroke.h": "./include/agg_vcgen_stroke.h",
        "agg_vcgen_vertex_sequence.h": "./include/agg_vcgen_vertex_sequence.h",
        "agg_vertex_sequence.h": "./include/agg_vertex_sequence.h",
        "agg_vpgen_clip_polygon.h": "./include/agg_vpgen_clip_polygon.h",
        "agg_vpgen_clip_polyline.h": "./include/agg_vpgen_clip_polyline.h",
        "agg_vpgen_segmentator.h": "./include/agg_vpgen_segmentator.h",
    },
)
