load("@rules_java//java:defs.bzl", "java_library", "java_test")

package(default_visibility = ["//visibility:public"])

java_library(
    name = "testlib",
    srcs = ["GenericTreeFileSystemTest.java"],
    deps = [
        "//java/com/cowlark/fluxengine/config",
        "//java/com/cowlark/fluxengine/config:common_java_proto",
        "//java/com/cowlark/fluxengine/config:config_java_proto",
        "//java/com/cowlark/fluxengine/core",
        "//java/com/cowlark/fluxengine/data",
        "//java/com/cowlark/fluxengine/imagewriter",
        "//java/com/cowlark/fluxengine/imagewriter:imagewriter_java_proto",
        "//java/com/cowlark/fluxengine/vfs",
        "//javatests/com/cowlark/fluxengine/testing",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)

java_test(
    name = "InMemoryBlockDeviceTest",
    srcs = ["InMemoryBlockDeviceTest.java"],
    deps = [
        "//java/com/cowlark/fluxengine/config",
        "//java/com/cowlark/fluxengine/config:config_java_proto",
        "//java/com/cowlark/fluxengine/core",
        "//java/com/cowlark/fluxengine/data",
        "//java/com/cowlark/fluxengine/vfs",
        "//javatests/com/cowlark/fluxengine/testing",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)

java_test(
    name = "VfsPathTest",
    srcs = ["VfsPathTest.java"],
    deps = [
        "//java/com/cowlark/fluxengine/vfs",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)

java_test(
    name = "TrackedBlockDeviceTest",
    srcs = ["TrackedBlockDeviceTest.java"],
    deps = [
        "//java/com/cowlark/fluxengine/config",
        "//java/com/cowlark/fluxengine/config:config_java_proto",
        "//java/com/cowlark/fluxengine/core",
        "//java/com/cowlark/fluxengine/data",
        "//java/com/cowlark/fluxengine/vfs",
        "//javatests/com/cowlark/fluxengine/testing",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)

java_test(
    name = "FatFileSystemTest",
    srcs = ["FatFileSystemTest.java"],
    deps = [
        ":testlib",
        "//java/com/cowlark/fluxengine/config",
        "//java/com/cowlark/fluxengine/config:common_java_proto",
        "//java/com/cowlark/fluxengine/config:config_java_proto",
        "//java/com/cowlark/fluxengine/core",
        "//java/com/cowlark/fluxengine/data",
        "//java/com/cowlark/fluxengine/imagewriter",
        "//java/com/cowlark/fluxengine/imagewriter:imagewriter_java_proto",
        "//java/com/cowlark/fluxengine/vfs",
        "//javatests/com/cowlark/fluxengine/testing",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)

java_test(
    name = "AmigaFileSystemTest",
    srcs = ["AmigaFileSystemTest.java"],
    deps = [
        ":testlib",
        "//java/com/cowlark/fluxengine/config",
        "//java/com/cowlark/fluxengine/config:common_java_proto",
        "//java/com/cowlark/fluxengine/config:config_java_proto",
        "//java/com/cowlark/fluxengine/core",
        "//java/com/cowlark/fluxengine/data",
        "//java/com/cowlark/fluxengine/imagewriter",
        "//java/com/cowlark/fluxengine/imagewriter:imagewriter_java_proto",
        "//java/com/cowlark/fluxengine/vfs",
        "//javatests/com/cowlark/fluxengine/testing",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)

java_test(
    name = "MacHfsFilesystemTest",
    srcs = ["MacHfsFilesystemTest.java"],
    deps = [
        ":testlib",
        "//java/com/cowlark/fluxengine/config",
        "//java/com/cowlark/fluxengine/config:common_java_proto",
        "//java/com/cowlark/fluxengine/config:config_java_proto",
        "//java/com/cowlark/fluxengine/core",
        "//java/com/cowlark/fluxengine/data",
        "//java/com/cowlark/fluxengine/imagewriter",
        "//java/com/cowlark/fluxengine/imagewriter:imagewriter_java_proto",
        "//java/com/cowlark/fluxengine/vfs",
        "//javatests/com/cowlark/fluxengine/testing",
        "//third_party/java/org/mars/hfsutils",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)

java_test(
    name = "AppleSingleTest",
    srcs = ["AppleSingleTest.java"],
    deps = [
        "//java/com/cowlark/fluxengine/core",
        "//java/com/cowlark/fluxengine/vfs",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)
