load("@com_google_protobuf//bazel:java_proto_library.bzl", "java_proto_library")
load("@rules_java//java:defs.bzl", "java_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "vfs_proto",
    srcs = ["vfs.proto"],
    strip_import_prefix = "/java/",
    deps = ["//java/com/cowlark/fluxengine/config:common_proto"],
)

java_proto_library(
    name = "vfs_java_proto",
    deps = [":vfs_proto"],
)

java_library(
    name = "vfs",
    srcs = glob(["*.java"]),
    plugins = ["//java/com/cowlark/fluxengine/wiring:lombok_plugin"],
    deps = [
        "@maven//:com_google_guava_guava",
        "@maven//:org_projectlombok_lombok",
        "@maven//:org_slf4j_slf4j_api",
    ],
)
