load("@rules_java//java:defs.bzl", "java_test")

package(default_visibility = ["//visibility:public"])

java_test(
    name = "PreferencesReaderWriterTest",
    srcs = ["PreferencesReaderWriterTest.java"],
    deps = [
        "//java/com/cowlark/fluxengine/gui",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:net_bytebuddy_byte_buddy",
        "@maven//:net_bytebuddy_byte_buddy_agent",
        "@maven//:org_mockito_mockito_core",
        "@maven//:org_objenesis_objenesis",
    ],
)
