package com.cowlark.fluxengine.buildtools;

import com.cowlark.fluxengine.config.ConfigProto;
import com.cowlark.fluxengine.config.OptionGroupProto;
import com.cowlark.fluxengine.config.OptionProto;
import com.cowlark.fluxengine.data.Formats;
import com.google.common.collect.ImmutableList;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

public class MkDoc
{
    private MkDoc()
    {
    }

    private record DocumentationWriter(ConfigProto config, String name, PrintWriter writer)
    {
        private void addExample(
                ImmutableList.Builder<String> examples,
                boolean write,
                String name,
                OptionProto format)
        {
            ConfigProto.Builder builder = config.toBuilder();
            if (format != null)
                builder.mergeFrom(format.getConfig());
            ConfigProto merged = builder.build();

            String r;
            if (write && merged.hasEncoder())
                r = "fluxengine write";
            else if (!write && merged.hasDecoder())
                r = "fluxengine read";
            else
                return;

            r += " -c " + name;
            if (format != null)
                r += " --" + format.getName();

            String filename = write ?
                    merged.getImageReader().getFilename() :
                    merged.getImageWriter().getFilename();
            if (filename.isEmpty())
                filename = name + ".img";

            r += write ? (" -d drive:0 -i " + filename) : (" -s drive:0 -o " + filename);

            examples.add(r);
        }

        private void printExamples(boolean write, String name, OptionGroupProto formatGroup)
        {
            ImmutableList.Builder<String> examples = ImmutableList.builder();
            if (formatGroup != null)
            {
                for (OptionProto option : formatGroup.getOptionList())
                    addExample(examples, write, name, option);
            } else
                addExample(examples, write, name, null);

            ImmutableList<String> list = examples.build();
            if (!list.isEmpty())
            {
                writer.printf("%s:%n%n", write ? "To write" : "To read");
                for (String e : list)
                    writer.printf("  - `%s`%n", e);
                writer.println();
            }
        }

        public void write()
        {

            writer.printf("%s%n====%n", config.getShortname());
            writer.printf("## %s%n", config.getComment());
            writer.print("<!-- This file is automatically generated. Do not edit. -->\n\n");

            List<String> documentation = config.getDocumentationList();
            if (!documentation.isEmpty())
            {
                writer.printf("%s%n", documentation.get(0));

                if (!config.getIsExtension())
                {
                    writer.print("## Options\n\n");

                    OptionGroupProto formatGroup = null;
                    if (!config.getOptionList().isEmpty() || !config.getOptionGroupList().isEmpty())
                    {
                        for (OptionGroupProto optionGroup : config.getOptionGroupList())
                        {
                            String groupName = optionGroup.getComment();
                            if (groupName.equals("$formats"))
                            {
                                groupName = "Format variants";
                                formatGroup = optionGroup;
                            }

                            writer.printf("  - %s:%n", groupName);
                            for (OptionProto option : optionGroup.getOptionList())
                                writer.printf(
                                        "      - `%s`: %s%n",
                                        option.getName(),
                                        option.getComment());
                        }

                        for (OptionProto option : config.getOptionList())
                            writer.printf("  - `%s`: %s%n", option.getName(), option.getComment());
                    } else
                        writer.print("(no options)\n");
                    writer.println();

                    writer.print("## Examples\n\n");

                    printExamples(false, name, formatGroup);
                    printExamples(true, name, formatGroup);
                }

                for (int i = 1; i < documentation.size(); i++)
                    writer.printf("%s%n", documentation.get(i));
            } else
                writer.print("(This format has no documentation. Please file a bug.)\n");
        }
    }

    public static void main(String[] args) throws IOException
    {
        File dir = new File(args[0]);

        for (String name : Formats.all())
        {
            ConfigProto config = Formats.get(name);
            File outputFile = new File(dir, String.format("disk-%s.md", name));
            try (PrintWriter writer = new PrintWriter(new FileOutputStream(outputFile)))
            {
                new DocumentationWriter(config, name, writer).write();
            }
        }
    }
}
