from build.pkg import package
from build.c import clibrary, cxxlibrary
from build.git import git_repository

package(
    name="fmt_lib",
    package="fmt",
    fallback=cxxlibrary(
        name="fmt_fallback_lib",
        srcs=[
            "dep/fmt/src/format.cc",
            "dep/fmt/src/os.cc",
        ],
        hdrs={
            h: f"dep/fmt/include/{h}"
            for h in [
                "fmt/args.h",
                "fmt/base.h",
                "fmt/chrono.h",
                "fmt/color.h",
                "fmt/compile.h",
                "fmt/core.h",
                "fmt/format.h",
                "fmt/format-inl.h",
                "fmt/os.h",
                "fmt/ostream.h",
                "fmt/printf.h",
                "fmt/ranges.h",
                "fmt/std.h",
                "fmt/xchar.h",
            ]
        },
        deps=[
            git_repository(
                name="fmt_repo",
                url="https://github.com/fmtlib/fmt",
                branch="11.1.4",
                path="dep/fmt",
            )
        ],
    ),
)

package(
    name="md4c_lib",
    package="md4c",
    fallback=clibrary(
        name="md4c_fallback_lib",
        srcs=[
            "dep/md4c/src/entity.c",
            "dep/md4c/src/entity.h",
            "dep/md4c/src/md4c-html.h",
            "dep/md4c/src/md4c.c",
            "dep/md4c/src/md4c.h",
        ],
        hdrs={"md4c.h": "dep/md4c/src/md4c.h"},
        deps=[
            git_repository(
                name="md4c_repo",
                url="https://github.com/mity/md4c",
                branch="master",
                path="dep/md4c",
            )
        ],
    ),
)

cxxlibrary(
    name="lexy_lib",
    hdrs={
        h: f"dep/lexy/include/{h}"
        for h in [
            "lexy_ext/parse_tree_algorithm.hpp",
            "lexy_ext/report_error.hpp",
            "lexy_ext/parse_tree_doctest.hpp",
            "lexy_ext/compiler_explorer.hpp",
            "lexy_ext/shell.hpp",
            "lexy/callback/constant.hpp",
            "lexy/callback/object.hpp",
            "lexy/callback/composition.hpp",
            "lexy/callback/aggregate.hpp",
            "lexy/callback/forward.hpp",
            "lexy/callback/integer.hpp",
            "lexy/callback/string.hpp",
            "lexy/callback/bit_cast.hpp",
            "lexy/callback/bind.hpp",
            "lexy/callback/fold.hpp",
            "lexy/callback/adapter.hpp",
            "lexy/callback/container.hpp",
            "lexy/callback/noop.hpp",
            "lexy/callback/base.hpp",
            "lexy/error.hpp",
            "lexy/_detail/type_name.hpp",
            "lexy/_detail/assert.hpp",
            "lexy/_detail/swar.hpp",
            "lexy/_detail/tuple.hpp",
            "lexy/_detail/code_point.hpp",
            "lexy/_detail/unicode_database.hpp",
            "lexy/_detail/integer_sequence.hpp",
            "lexy/_detail/any_ref.hpp",
            "lexy/_detail/memory_resource.hpp",
            "lexy/_detail/iterator.hpp",
            "lexy/_detail/config.hpp",
            "lexy/_detail/stateless_lambda.hpp",
            "lexy/_detail/lazy_init.hpp",
            "lexy/_detail/nttp_string.hpp",
            "lexy/_detail/detect.hpp",
            "lexy/_detail/string_view.hpp",
            "lexy/_detail/buffer_builder.hpp",
            "lexy/_detail/invoke.hpp",
            "lexy/_detail/std.hpp",
            "lexy/code_point.hpp",
            "lexy/parse_tree.hpp",
            "lexy/grammar.hpp",
            "lexy/encoding.hpp",
            "lexy/input_location.hpp",
            "lexy/lexeme.hpp",
            "lexy/dsl/capture.hpp",
            "lexy/dsl/case_folding.hpp",
            "lexy/dsl/literal.hpp",
            "lexy/dsl/context_identifier.hpp",
            "lexy/dsl/error.hpp",
            "lexy/dsl/whitespace.hpp",
            "lexy/dsl/flags.hpp",
            "lexy/dsl/subgrammar.hpp",
            "lexy/dsl/code_point.hpp",
            "lexy/dsl/sign.hpp",
            "lexy/dsl/member.hpp",
            "lexy/dsl/if.hpp",
            "lexy/dsl/symbol.hpp",
            "lexy/dsl/branch.hpp",
            "lexy/dsl/follow.hpp",
            "lexy/dsl/repeat.hpp",
            "lexy/dsl/ascii.hpp",
            "lexy/dsl/combination.hpp",
            "lexy/dsl/return.hpp",
            "lexy/dsl/integer.hpp",
            "lexy/dsl/production.hpp",
            "lexy/dsl/until.hpp",
            "lexy/dsl/brackets.hpp",
            "lexy/dsl/sequence.hpp",
            "lexy/dsl/char_class.hpp",
            "lexy/dsl/lookahead.hpp",
            "lexy/dsl/loop.hpp",
            "lexy/dsl/unicode.hpp",
            "lexy/dsl/context_counter.hpp",
            "lexy/dsl/choice.hpp",
            "lexy/dsl/parse_as.hpp",
            "lexy/dsl/byte.hpp",
            "lexy/dsl/digit.hpp",
            "lexy/dsl/punctuator.hpp",
            "lexy/dsl/recover.hpp",
            "lexy/dsl/times.hpp",
            "lexy/dsl/bits.hpp",
            "lexy/dsl/option.hpp",
            "lexy/dsl/identifier.hpp",
            "lexy/dsl/context_flag.hpp",
            "lexy/dsl/operator.hpp",
            "lexy/dsl/token.hpp",
            "lexy/dsl/any.hpp",
            "lexy/dsl/separator.hpp",
            "lexy/dsl/peek.hpp",
            "lexy/dsl/newline.hpp",
            "lexy/dsl/parse_tree_node.hpp",
            "lexy/dsl/expression.hpp",
            "lexy/dsl/delimited.hpp",
            "lexy/dsl/effect.hpp",
            "lexy/dsl/position.hpp",
            "lexy/dsl/scan.hpp",
            "lexy/dsl/list.hpp",
            "lexy/dsl/base.hpp",
            "lexy/dsl/bom.hpp",
            "lexy/dsl/terminator.hpp",
            "lexy/dsl/eof.hpp",
            "lexy/dsl.hpp",
            "lexy/visualize.hpp",
            "lexy/callback.hpp",
            "lexy/token.hpp",
            "lexy/action/parse_as_tree.hpp",
            "lexy/action/parse.hpp",
            "lexy/action/trace.hpp",
            "lexy/action/match.hpp",
            "lexy/action/validate.hpp",
            "lexy/action/scan.hpp",
            "lexy/action/base.hpp",
            "lexy/input/buffer.hpp",
            "lexy/input/lexeme_input.hpp",
            "lexy/input/argv_input.hpp",
            "lexy/input/file.hpp",
            "lexy/input/string_input.hpp",
            "lexy/input/parse_tree_input.hpp",
            "lexy/input/range_input.hpp",
            "lexy/input/base.hpp",
        ]
    },
    deps=[
        git_repository(
            name="lexy_repo",
            url="https://github.com/foonathan/lexy",
            branch="v2025.05.0",
            path="dep/lexy",
        )
    ],
)

cxxlibrary(
    name="snowhouse_lib",
    hdrs={
        h: f"dep/snowhouse/include/{h}"
        for h in [
            "snowhouse/snowhouse.h",
            "snowhouse/assert.h",
            "snowhouse/fluent/fluent.h",
            "snowhouse/fluent/constraintadapter.h",
            "snowhouse/fluent/constraintlist.h",
            "snowhouse/fluent/operators/andoperator.h",
            "snowhouse/fluent/operators/invalidexpressionexception.h",
            "snowhouse/fluent/operators/collections/collectionoperator.h",
            "snowhouse/fluent/operators/collections/collectionconstraintevaluator.h",
            "snowhouse/fluent/operators/collections/atleastoperator.h",
            "snowhouse/fluent/operators/collections/noneoperator.h",
            "snowhouse/fluent/operators/collections/atmostoperator.h",
            "snowhouse/fluent/operators/collections/alloperator.h",
            "snowhouse/fluent/operators/collections/exactlyoperator.h",
            "snowhouse/fluent/operators/notoperator.h",
            "snowhouse/fluent/operators/constraintoperator.h",
            "snowhouse/fluent/operators/oroperator.h",
            "snowhouse/fluent/expressionbuilder.h",
            "snowhouse/assertionexception.h",
            "snowhouse/exceptions.h",
            "snowhouse/stringizers.h",
            "snowhouse/macros.h",
            "snowhouse/constraints/equalscontainerconstraint.h",
            "snowhouse/constraints/islessthanorequaltoconstraint.h",
            "snowhouse/constraints/equalsconstraint.h",
            "snowhouse/constraints/isgreaterthanconstraint.h",
            "snowhouse/constraints/fulfillsconstraint.h",
            "snowhouse/constraints/endswithconstraint.h",
            "snowhouse/constraints/constraints.h",
            "snowhouse/constraints/haslengthconstraint.h",
            "snowhouse/constraints/startswithconstraint.h",
            "snowhouse/constraints/equalswithdeltaconstraint.h",
            "snowhouse/constraints/isgreaterthanorequaltoconstraint.h",
            "snowhouse/constraints/containsconstraint.h",
            "snowhouse/constraints/islessthanconstraint.h",
            "snowhouse/constraints/isemptyconstraint.h",
            "snowhouse/constraints/expressions/andexpression.h",
            "snowhouse/constraints/expressions/orexpression.h",
            "snowhouse/constraints/expressions/expression_fwd.h",
            "snowhouse/constraints/expressions/notexpression.h",
            "snowhouse/constraints/expressions/expression.h",
            "snowhouse/stringize.h",
        ]
    },
    deps=[
        git_repository(
            name="snowhouse_repo",
            url="https://github.com/banditcpp/snowhouse",
            branch="v5.0.0",
            path="dep/snowhouse",
        )
    ],
)

package(
    name="cli11_lib",
    package="CLI11",
    fallback=cxxlibrary(
        name="cli11_fallback_lib",
        srcs=[],
        hdrs={
            h: f"dep/cli11/include/{h}"
            for h in [
                "CLI/Error.hpp",
                "CLI/App.hpp",
                "CLI/ExtraValidators.hpp",
                "CLI/ConfigFwd.hpp",
                "CLI/impl/Encoding_inl.hpp",
                "CLI/impl/Config_inl.hpp",
                "CLI/impl/Split_inl.hpp",
                "CLI/impl/Validators_inl.hpp",
                "CLI/impl/ExtraValidators_inl.hpp",
                "CLI/impl/App_inl.hpp",
                "CLI/impl/Option_inl.hpp",
                "CLI/impl/Formatter_inl.hpp",
                "CLI/impl/StringTools_inl.hpp",
                "CLI/impl/Argv_inl.hpp",
                "CLI/Split.hpp",
                "CLI/Version.hpp",
                "CLI/Config.hpp",
                "CLI/StringTools.hpp",
                "CLI/TypeTools.hpp",
                "CLI/FormatterFwd.hpp",
                "CLI/CLI.hpp",
                "CLI/Macros.hpp",
                "CLI/Formatter.hpp",
                "CLI/Option.hpp",
                "CLI/Argv.hpp",
                "CLI/Encoding.hpp",
                "CLI/Validators.hpp",
                "CLI/Timer.hpp",
            ]
        },
        deps=[
            git_repository(
                name="cli11_repo",
                url="https://github.com/CLIUtils/CLI11",
                branch="v2.6.1",
                path="dep/cli11",
            )
        ],
    ),
)

package(
    name="nlohmannjson_lib",
    package="nlohmann_json",
    fallback=cxxlibrary(
        name="nlohmannjson_fallback_lib",
        srcs=[],
        hdrs={
            h: f"dep/nlohmann_json/single_include/{h}"
            for h in ["nlohmann/json_fwd.hpp", "nlohmann/json.hpp"]
        },
        deps=[
            git_repository(
                name="nlohmannjson_repo",
                url="https://github.com/nlohmann/json",
                branch="v3.12.0",
                path="dep/nlohmann_json",
            )
        ],
    ),
)

cxxlibrary(
    name="libthrowingptr",
    srcs=[],
    hdrs={
        h: f"dep/throwing_ptr/include/{h}"
        for h in [
            "throwing/unique_ptr.hpp",
            "throwing/private/clear_compiler_checks.hpp",
            "throwing/private/compiler_checks.hpp",
            "throwing/shared_ptr.hpp",
            "throwing/null_ptr_exception.hpp",
        ]
    },
    deps=[
        git_repository(
            name="libthrowingptr_repo",
            url="https://github.com/rockdreamer/throwing_ptr",
            branch="master",
            path="dep/throwing_ptr",
        )
    ],
)

cxxlibrary(
    name="xdgpp_lib",
    srcs=[],
    hdrs={"xdg.hpp": "dep/xdgpp/xdg.hpp"},
    deps=[
        git_repository(
            name="xdgpp_repo",
            url="https://github.com/WerWolv/xdgpp",
            branch="master",
            path="dep/xdgpp",
        )
    ],
)

package(
    name="plutovg_lib",
    package="plutovg",
    fallback=clibrary(
        name="plutovg_fallback_lib",
        srcs=[
            "dep/plutovg/source/plutovg-canvas.c",
            "dep/plutovg/source/plutovg-ft-math.c",
            "dep/plutovg/source/plutovg-surface.c",
            "dep/plutovg/source/plutovg-font.c",
            "dep/plutovg/source/plutovg-ft-math.h",
            "dep/plutovg/source/plutovg-ft-stroker.h",
            "dep/plutovg/source/plutovg-rasterize.c",
            "dep/plutovg/source/plutovg-stb-image-write.h",
            "dep/plutovg/source/plutovg-blend.c",
            "dep/plutovg/source/plutovg-ft-stroker.c",
            "dep/plutovg/source/plutovg-private.h",
            "dep/plutovg/source/plutovg-ft-raster.h",
            "dep/plutovg/source/plutovg-ft-types.h",
            "dep/plutovg/source/plutovg-stb-image.h",
            "dep/plutovg/source/plutovg-stb-truetype.h",
            "dep/plutovg/source/plutovg-paint.c",
            "dep/plutovg/source/plutovg-matrix.c",
            "dep/plutovg/source/plutovg-ft-raster.c",
            "dep/plutovg/source/plutovg-utils.h",
            "dep/plutovg/source/plutovg-path.c",
        ],
        hdrs={"plutovg.h": "dep/plutovg/include/plutovg.h"},
        deps=[
            git_repository(
                name="plutovg_repo",
                url="https://github.com/sammycage/plutovg",
                branch="v1.3.2",
                path="dep/plutovg",
            )
        ],
    ),
)

package(
    name="lunasvg",
    package="lunasvg",
    fallback=cxxlibrary(
        name="lunasvg_fallback_lib",
        srcs=[
            "dep/lunasvg/source/svgtextelement.cpp",
            "dep/lunasvg/source/lunasvg.cpp",
            "dep/lunasvg/source/graphics.h",
            "dep/lunasvg/source/svggeometryelement.cpp",
            "dep/lunasvg/source/svgproperty.cpp",
            "dep/lunasvg/source/graphics.cpp",
            "dep/lunasvg/source/svgpaintelement.cpp",
            "dep/lunasvg/source/svgparser.cpp",
            "dep/lunasvg/source/svgelement.cpp",
            "dep/lunasvg/source/svgrenderstate.h",
            "dep/lunasvg/source/svgproperty.h",
            "dep/lunasvg/source/svgpaintelement.h",
            "dep/lunasvg/source/svgelement.h",
            "dep/lunasvg/source/svgtextelement.h",
            "dep/lunasvg/source/svggeometryelement.h",
            "dep/lunasvg/source/svgparserutils.h",
            "dep/lunasvg/source/svglayoutstate.cpp",
            "dep/lunasvg/source/svglayoutstate.h",
            "dep/lunasvg/source/svgrenderstate.cpp",
        ],
        hdrs={"lunasvg.h": "dep/lunasvg/include/lunasvg.h"},
        deps=[
            "dep+plutovg_lib",
            "dep+fmt_lib",
            git_repository(
                name="lunasvg_repo",
                url="https://github.com/sammycage/lunasvg",
                branch="v3.5.0",
                path="dep/lunasvg",
            ),
        ],
        cflags=[
            "-DLUNASVG_BUILD_STATIC",
            "-DPLUTOVG_BUILD_STATIC",
        ],
        caller_cflags=[
            "-DLUNASVG_BUILD_STATIC",
            "-DPLUTOVG_BUILD_STATIC",
        ],
    ),
)
