package com.cowlark.fluxengine.arch.agat;

import com.cowlark.fluxengine.core.Bits;
import com.cowlark.fluxengine.core.Bytes;
import com.cowlark.fluxengine.data.FluxMatchers;
import com.cowlark.fluxengine.data.FluxPattern;
import com.cowlark.fluxengine.data.LogicalLocation;
import com.cowlark.fluxengine.data.Sector;
import com.cowlark.fluxengine.decoders.Decoder;
import com.cowlark.fluxengine.decoders.DecoderProto;
import com.cowlark.fluxengine.external.FmMfm;

/**
 * The Agat decoder, ported from arch/agat/decoder.cc.
 */
public class AgatDecoder extends Decoder
{
    /*
     * data:    X  X  X  X   X  X  X  X   X  -  -  X   -  X  -  X   -  X  X  -   X  -  X  -  = 0xff956a
     * flux:   01 01 01 01  01 01 01 01  01 00 10 01  00 01 00 01  00 01 01 00  01 00 01 00  = 0x555549111444
     *
     * data:    X  X  X  X   X  X  X  X   -  X  X  -   X  -  X  -   X  -  -  X   -  X  -  X  = 0xff6a95
     * flux:   01 01 01 01  01 01 01 01  00 01 01 00  01 00 01 00  01 00 10 01  00 01 00 01  = 0x555514444911
     *
     * Each pattern is prefixed with this one:
     *
     * data:          -  -   -  X   -  -   X  - = 0x12
     * flux:    (10) 10 10  10 01  00 10  01 00 = 0xa924
     * magic:   (10) 10 00  10 01  00 10  01 00 = 0x8924
     *                  ^
     *
     * This seems to be generated by emitting A4 in MFM and then a single 0 bit
     * to shift it out of phase, so the data bits become clock bits and vice
     * versa.
     *
     *           X - X - - X - -  = 0xA4
     *          0100010010010010  = MFM encoded
     *           1000100100100100 = with trailing zero
     *            - - - X - - X - = effective bitstream = 0x12
     */
    private static final FluxPattern SECTOR_PATTERN = new FluxPattern(64, Agat.SECTOR_ID);
    private static final FluxPattern DATA_PATTERN = new FluxPattern(64, Agat.DATA_ID);

    private static final FluxMatchers ALL_PATTERNS = FluxMatchers.of(SECTOR_PATTERN, DATA_PATTERN);

    public AgatDecoder(DecoderProto config)
    {
        super(config);
    }

    @Override
    protected double advanceToNextRecord()
    {
        return seekToPattern(ALL_PATTERNS);
    }

    @Override
    protected void decodeSectorRecord()
    {
        if (readRaw64() != Agat.SECTOR_ID)
            return;

        Bytes bytes = FmMfm.decodeFmMfm(readRawBits(64)).slice(0, 4);
        if (bytes.getByte(3) != 0x5a)
            return;

        int logicalCylinder = (bytes.getByte(1) & 0xff) >> 1;
        int logicalSector = bytes.getByte(2) & 0xff;
        int logicalHead = bytes.getByte(1) & 1;
        sector.location = new LogicalLocation(logicalCylinder, logicalHead, logicalSector);
        sector.status = Sector.Status.DATA_MISSING;
    }

    @Override
    protected void decodeDataRecord()
    {
        if (readRaw64() != Agat.DATA_ID)
            return;

        Bytes bytes = FmMfm.decodeFmMfm(readRawBits((Agat.AGAT_SECTOR_SIZE + 2) * 16))
                .slice(0, Agat.AGAT_SECTOR_SIZE + 2);

        if (bytes.getByte(Agat.AGAT_SECTOR_SIZE + 1) != 0x5a)
            return;

        sector.data = bytes.slice(0, Agat.AGAT_SECTOR_SIZE);
        int wantChecksum = bytes.getByte(Agat.AGAT_SECTOR_SIZE) & 0xff;
        int gotChecksum = Agat.agatChecksum(sector.data);
        sector.status =
                (wantChecksum == gotChecksum) ? Sector.Status.OK : Sector.Status.BAD_CHECKSUM;
    }
}