/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this
 * license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.cowlark.fluxengine.gui;

import javax.swing.KeyStroke;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;

/**
 *
 * @author dg
 */
public class ApplicationFrame extends javax.swing.JFrame
{

    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(ApplicationFrame.class.getName());

    /**
     * Creates new form ApplicationFrame
     */
    public ApplicationFrame()
    {
        initComponents();
        statusBarPanel.putClientProperty("FlatLaf.style", "margin: 2,8,2,8");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        statusBarPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane3 = new javax.swing.JSplitPane();
        jSplitPane4 = new javax.swing.JSplitPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel8.setText("Status bar");
        statusBarPanel.add(jLabel8);

        getContentPane().add(statusBarPanel, java.awt.BorderLayout.PAGE_END);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(1.0);

        jSplitPane4.setResizeWeight(0.5);

        jLabel6.setText("Left pane");
        jPanel3.add(jLabel6);

        jScrollPane7.setViewportView(jPanel3);

        jTabbedPane3.addTab("tab1", jScrollPane7);

        jSplitPane4.setLeftComponent(jTabbedPane3);

        jLabel3.setText("jLabel3");
        jPanel4.add(jLabel3);

        jScrollPane4.setViewportView(jPanel4);

        jTabbedPane4.addTab("tab1", jScrollPane4);

        jSplitPane4.setRightComponent(jTabbedPane4);

        jSplitPane3.setRightComponent(jSplitPane4);

        jLabel4.setText("Configuration pane");
        jPanel1.add(jLabel4);

        jScrollPane5.setViewportView(jPanel1);

        jSplitPane3.setLeftComponent(jScrollPane5);

        jSplitPane1.setLeftComponent(jSplitPane3);

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(100, 100));

        jPanel2.setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        jButton2.setText("jButton2");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jPanel2.add(jToolBar1, java.awt.BorderLayout.SOUTH);

        jTabbedPane1.addTab("Actions", jPanel2);
        jPanel2.getAccessibleContext().setAccessibleName("");

        jScrollPane1.setMaximumSize(new java.awt.Dimension(32767, 200));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(100, 200));

        jLabel7.setText("Logging window");
        jPanel5.add(jLabel7);

        jScrollPane1.setViewportView(jPanel5);

        jTabbedPane1.addTab("Logging", jScrollPane1);

        jSplitPane1.setRightComponent(jTabbedPane1);
        jTabbedPane1.getAccessibleContext().setAccessibleName("Actions");

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        aboutMenuItem.setText("About...");
        aboutMenuItem.addActionListener(this::aboutMenuItemActionPerformed);
        jMenu1.add(aboutMenuItem);
        jMenu1.add(jSeparator1);

        exitMenuItem.setText("Exit");
        jMenu1.add(exitMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        cutMenuItem.setAccelerator(createMenuAccelerator(KeyEvent.VK_X));
        cutMenuItem.setText("Cut");
        jMenu2.add(cutMenuItem);

        copyMenuItem.setAccelerator(createMenuAccelerator(KeyEvent.VK_C));
        copyMenuItem.setText("Copy");
        copyMenuItem.addActionListener(this::copyMenuItemActionPerformed);
        jMenu2.add(copyMenuItem);

        pasteMenuItem.setAccelerator(createMenuAccelerator(KeyEvent.VK_V));
        pasteMenuItem.setText("Paste");
        jMenu2.add(pasteMenuItem);

        deleteMenuItem.setAccelerator(createMenuAccelerator(KeyEvent.VK_DELETE));
        deleteMenuItem.setText("Delete");
        jMenu2.add(deleteMenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private static KeyStroke createMenuAccelerator(int keyCode)
    {
        int mask = Toolkit.getDefaultToolkit().getMenuShortcutKeyMaskEx();
        return KeyStroke.getKeyStroke(keyCode, mask);
    }

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void copyMenuItemActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_copyMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_copyMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JPanel statusBarPanel;
    // End of variables declaration//GEN-END:variables
}
