load("@rules_java//java:defs.bzl", "java_binary", "java_library")

package(default_visibility = ["//visibility:public"])

java_library(
    name = "gui",
    srcs = glob(["*.java"]),
    deps = [
        "@maven//:org_openjfx_javafx_base",
        "@maven//:org_openjfx_javafx_base_linux",
        "@maven//:org_openjfx_javafx_controls",
        "@maven//:org_openjfx_javafx_controls_linux",
        "@maven//:org_openjfx_javafx_graphics",
        "@maven//:org_openjfx_javafx_graphics_linux",
    ],
)
