load("@rules_proto//proto:defs.bzl", "proto_library")
load("@com_google_protobuf//bazel:java_proto_library.bzl", "java_proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "encoders_proto",
    srcs = ["encoders.proto"],
    strip_import_prefix = "/java/",
    deps = ["//java/com/cowlark/fluxengine/arch:arch_proto"],
)

java_proto_library(
    name = "encoders_java_proto",
    deps = [":encoders_proto"],
)
