load("@rules_java//java:defs.bzl", "java_library")

package(default_visibility = ["//visibility:public"])

java_library(
    name = "flags",
    srcs = glob(["*.java"]),
    plugins = ["//java/com/cowlark/fluxengine/wiring:lombok_plugin"],
    deps = [
        "//java/com/cowlark/fluxengine/core",
        "@maven//:com_google_guava_guava",
        "@maven//:org_projectlombok_lombok",
    ],
)
