name: C/C++ CI

on: [ push ]

concurrency:
  group: environment-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'davidgiven/fluxengine'
          path: 'fluxengine'
      - uses: actions/checkout@v4
        with:
          repository: 'davidgiven/fluxengine-testdata'
          path: 'fluxengine-testdata'
      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.19.0
      - name: Build with Bazel
        run: |
          cd fluxengine
          bazel test //... --test_output=errors
          bazel build //:fluxengine //:fluxengine_deb //:fluxengine_rpm //:fluxengine_app_image
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}.${{ github.sha }}.bazel.artifacts
          path: |
            fluxengine/bazel-bin/**

  build-macos-current:
    strategy:
      matrix:
        runs-on: [ macos-15, macos-15-intel ]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'davidgiven/fluxengine'
          path: 'fluxengine'
      - uses: actions/checkout@v4
        with:
          repository: 'davidgiven/fluxengine-testdata'
          path: 'fluxengine-testdata'
      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.19.0
      - name: Build with Bazel
        run: |
          cd fluxengine
          bazel test //... --test_output=errors
          bazel build //:fluxengine //:fluxengine_dmg
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}.${{ github.sha }}.bazel.artifacts.${{ runner.arch }}
          path: |
            fluxengine/bazel-bin/**

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          pacboy: |
            p:png2ico

      - uses: actions/checkout@v4
        with:
          repository: 'davidgiven/fluxengine'
          path: 'fluxengine'

      - uses: actions/checkout@v4
        with:
          repository: 'davidgiven/fluxengine-testdata'
          path: 'fluxengine-testdata'

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.19.0

      - name: Set up MSVC Developer Environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Build with Bazel
        run: |
          $ErrorActionPreference = 'Stop'
          $PSNativeCommandUseErrorActionPreference = $true
          cd fluxengine
          bazel test //... --test_output=errors `
              --action_env=PATH `
              --action_env=INCLUDE `
              --action_env=LIB `
              --action_env=LIBPATH
          bazel build //:fluxengine //:fluxengine_msi `
              --action_env=PATH `
              --action_env=INCLUDE `
              --action_env=LIB `
              --action_env=LIBPATH

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}.${{ github.sha }}.bazel.artifacts.windows
          path: fluxengine/bazel-bin/**
