name: C/C++ CI

on: [push]

concurrency: 
  group: environment-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant:
        - debian12
        - debian13
        - fedora42
        - fedora43
        - fedora43.nooptionaldeps
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'davidgiven/fluxengine'
        path: 'fluxengine'
    - uses: actions/checkout@v4
      with:
        repository: 'davidgiven/fluxengine-testdata'
        path: 'fluxengine-testdata'
    - name: Setup Bazel
      uses: bazelbuild/setup-bazel@v4
      with:
        install-bazelisk: true
    - name: Build with Bazel
      run: |
        cd fluxengine
        bazel build //:all
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}.${{ github.sha }}.bazel.artifacts
        path: |
          fluxengine/bazel-bin/**

  build-macos-current:
    strategy:
      matrix:
        runs-on: [macos-15, macos-15-intel]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'davidgiven/fluxengine'
        path: 'fluxengine'
    - uses: actions/checkout@v4
      with:
        repository: 'davidgiven/fluxengine-testdata'
        path: 'fluxengine-testdata'
    - name: Setup Bazel
      uses: bazelbuild/setup-bazel@v4
      with:
        install-bazelisk: true
    - name: Build with Bazel
      run: |
        cd fluxengine
        bazel build //:all
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}.${{ github.sha }}.bazel.artifacts.${{ runner.arch }}
        path: |
          fluxengine/bazel-bin/**

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'davidgiven/fluxengine'
        path: 'fluxengine'

    - uses: actions/checkout@v4
      with:
        repository: 'davidgiven/fluxengine-testdata'
        path: 'fluxengine-testdata'

    - name: Setup Bazel
      uses: bazelbuild/setup-bazel@v4
      with:
        install-bazelisk: true

    - name: Build with Bazel
      run: |
        cd fluxengine
        bazel build //:all

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}.${{ github.sha }}.bazel.artifacts.windows
        path: fluxengine/bazel-bin/**
