name: Autorelease

concurrency:
  group: environment-release-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "master"

jobs:
  build-linux:
    strategy:
      matrix:
        runs-on: [ ubuntu-26.04, ubuntu-26.04-arm ]
    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'davidgiven/fluxengine'
          path: 'fluxengine'

      - uses: actions/checkout@v4
        with:
          repository: 'davidgiven/fluxengine-testdata'
          path: 'fluxengine-testdata'

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.19.0

      - name: Build with Bazel
        run: |
          cd fluxengine
          bazel test //... //:fluxengine_deb //:fluxengine_rpm //:fluxengine_app_image --test_output=errors
          mv bazel-bin/java/com/cowlark/fluxengine/fluxengine_1.0.0.deb fluxengine-1.0.0.${{ runner.arch }}.deb
          mv bazel-bin/java/com/cowlark/fluxengine/fluxengine_1.0.0.rpm fluxengine-1.0.0.${{ runner.arch }}.rpm
          mv bazel-bin/java/com/cowlark/fluxengine/fluxengine_1.0.0.tar.xz fluxengine-1.0.0.${{ runner.arch }}.tar.xz


      - name: date
        run: |
          echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}

      - name: tag
        uses: EndBug/latest-tag@latest
        with:
          tag-name: dev
          force-branch: false
          git-directory: 'fluxengine'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: delete-old-assets
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ github.token }}
          tag: dev
          assets: |
            fluxengine-1.0.0.${{ runner.arch }}.deb
            fluxengine-1.0.0.${{ runner.arch }}.rpm
            fluxengine-1.0.0.${{ runner.arch }}.tar.xz
          fail-if-no-assets: false

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          name: Development build ${{ env.RELEASE_DATE }}
          files: |
            fluxengine/fluxengine-1.0.0.${{ runner.arch }}.deb
            fluxengine/fluxengine-1.0.0.${{ runner.arch }}.rpm
            fluxengine/fluxengine-1.0.0.${{ runner.arch }}.tar.xz
          tag_name: dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos-current:
    strategy:
      matrix:
        runs-on: [ macos-15, macos-15-intel ]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'davidgiven/fluxengine'
          path: 'fluxengine'

      - uses: actions/checkout@v4
        with:
          repository: 'davidgiven/fluxengine-testdata'
          path: 'fluxengine-testdata'

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.19.0

      - name: Build with Bazel
        run: |
          cd fluxengine
          bazel test //... //:fluxengine_dmg --test_output=errors
          mv bazel-bin/java/com/cowlark/fluxengine/fluxengine_1.0.0.dmg fluxengine_1.0.0.${{ runner.arch }}.dmg

      - name: date
        run: |
          echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}

      - name: tag
        uses: EndBug/latest-tag@latest
        with:
          tag-name: dev
          force-branch: false
          git-directory: 'fluxengine'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: delete-old-assets
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ github.token }}
          tag: dev
          assets: |
            fluxengine_1.0.0.${{ runner.arch }}.dmg
          fail-if-no-assets: false

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          name: Development build ${{ env.RELEASE_DATE }}
          files: |
            fluxengine/fluxengine_1.0.0.${{ runner.arch }}.dmg
          tag_name: dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  build-windows:
    strategy:
      matrix:
        runs-on: [ windows-latest, windows-11-arm ]
    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'davidgiven/fluxengine'
          path: 'fluxengine'

      - uses: actions/checkout@v4
        with:
          repository: 'davidgiven/fluxengine-testdata'
          path: 'fluxengine-testdata'

      - name: Setup software
        run: |
          winget install ImageMagick.ImageMagick --accept-source-agreements --accept-package-agreements

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.19.0

      - name: Set up MSVC Developer Environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Build with Bazel
        run: |
          $ErrorActionPreference = 'Stop'
          $PSNativeCommandUseErrorActionPreference = $true
          cd fluxengine
          bazel test //... //:fluxengine_msi --test_output=errors `
              --action_env=PATH `
              --action_env=INCLUDE `
              --action_env=LIB `
              --action_env=LIBPATH
          ren bazel-bin\java\com\cowlark\fluxengine\fluxengine_1.0.0.msi fluxengine-1.0.0.${{ runner.arch }}.msi

      - name: date
        run: |
          echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}

      - name: tag
        uses: EndBug/latest-tag@latest
        with:
          tag-name: dev
          force-branch: false
          git-directory: 'fluxengine'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: delete-old-assets
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ github.token }}
          tag: dev
          assets: |
            fluxengine-1.0.0.${{ runner.arch }}.msi
          fail-if-no-assets: false

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          name: Development build ${{ env.RELEASE_DATE }}
          files: |
            fluxengine/fluxengine-1.0.0.${{ runner.arch }}.msi
          tag_name: dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

