#ifndef SNOWHOUSE_MACROS_H
#define SNOWHOUSE_MACROS_H
// clang-format off

#define SNOWHOUSE_MAJOR 5
#define SNOWHOUSE_MINOR 0
#define SNOWHOUSE_PATCH 0

#define SNOWHOUSE_TOSTRING(x) #x
#define SNOWHOUSE_MACROTOSTRING(x) SNOWHOUSE_TOSTRING(x)
#define SNOWHOUSE_VERSION \
  SNOWHOUSE_MACROTOSTRING(SNOWHOUSE_MAJOR) "." \
  SNOWHOUSE_MACROTOSTRING(SNOWHOUSE_MINOR) "." \
  SNOWHOUSE_MACROTOSTRING(SNOWHOUSE_PATCH)
#endif
